// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PubgSDK.Helpers;

namespace PubgStatsBot.Migrations
{
    [DbContext(typeof(BotDBContext))]
    [Migration("20190922223109_matchIds")]
    partial class matchIds
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079");

            modelBuilder.Entity("PubgStatsBot.Model.Match", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("MatchId");

                    b.Property<int?>("PlayerID");

                    b.HasKey("Id");

                    b.HasIndex("PlayerID");

                    b.ToTable("Match");
                });

            modelBuilder.Entity("PubgStatsBot.Model.Player", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime?>("LastMatchNotified");

                    b.Property<string>("PubgID");

                    b.Property<int?>("UsersPlayersID");

                    b.HasKey("ID");

                    b.HasIndex("UsersPlayersID");

                    b.ToTable("Player");
                });

            modelBuilder.Entity("PubgStatsBot.Model.User", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<ulong>("DiscordId");

                    b.Property<string>("Name");

                    b.HasKey("ID");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("PubgStatsBot.Model.UsersPlayers", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("UserID");

                    b.HasKey("ID");

                    b.HasIndex("UserID");

                    b.ToTable("UsersPlayers");
                });

            modelBuilder.Entity("PubgStatsBot.Model.Match", b =>
                {
                    b.HasOne("PubgStatsBot.Model.Player")
                        .WithMany("Matches")
                        .HasForeignKey("PlayerID");
                });

            modelBuilder.Entity("PubgStatsBot.Model.Player", b =>
                {
                    b.HasOne("PubgStatsBot.Model.UsersPlayers")
                        .WithMany("Players")
                        .HasForeignKey("UsersPlayersID");
                });

            modelBuilder.Entity("PubgStatsBot.Model.UsersPlayers", b =>
                {
                    b.HasOne("PubgStatsBot.Model.User", "User")
                        .WithMany()
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
