//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PubgStatsBot {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PubgStatsBot.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adds player to your watch.
        /// </summary>
        internal static string AddWatchDesc {
            get {
                return ResourceManager.GetString("AddWatchDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compare two players stats.
        /// </summary>
        internal static string Compare {
            get {
                return ResourceManager.GetString("Compare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Players Duo Stats.
        /// </summary>
        internal static string DuoStats {
            get {
                return ResourceManager.GetString("DuoStats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        internal static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can use this bot via the commans listed below.
        /// </summary>
        internal static string HelpDescription {
            get {
                return ResourceManager.GetString("HelpDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add this bot to your server.
        /// </summary>
        internal static string InviteDesc {
            get {
                return ResourceManager.GetString("InviteDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is connected!.
        /// </summary>
        internal static string IsConnected {
            get {
                return ResourceManager.GetString("IsConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get the list of Pubg accounts added to your account.
        /// </summary>
        internal static string MyWatchDesc {
            get {
                return ResourceManager.GetString("MyWatchDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is Not a member.
        /// </summary>
        internal static string NotAMember {
            get {
                return ResourceManager.GetString("NotAMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You dont have a Watch yet. use the command !addWatch to add a player to your watch. for more information please use !help.
        /// </summary>
        internal static string NoWatchFound {
            get {
                return ResourceManager.GetString("NoWatchFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only members of Pubg stats can use this bot. please consider joining our server first.
        /// </summary>
        internal static string OnlyMembersCanUse {
            get {
                return ResourceManager.GetString("OnlyMembersCanUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player is successfully added to your watch. from now on whenever you play the a match you will recieve the match result. this function only works when you are online in discord. .
        /// </summary>
        internal static string PlayerAddedToWatch {
            get {
                return ResourceManager.GetString("PlayerAddedToWatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بازیکن قبلا برای شما ثبت شده است.
        /// </summary>
        internal static string PlayerIsAlreadySaved {
            get {
                return ResourceManager.GetString("PlayerIsAlreadySaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PlayerIsNotInYourWatch.
        /// </summary>
        internal static string PlayerIsNotInYourWatch {
            get {
                return ResourceManager.GetString("PlayerIsNotInYourWatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player name contains Space.
        /// </summary>
        internal static string PlayerNameHasSpace {
            get {
                return ResourceManager.GetString("PlayerNameHasSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player name is not given!.
        /// </summary>
        internal static string PlayerNameRequired {
            get {
                return ResourceManager.GetString("PlayerNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player with this name not found.
        /// </summary>
        internal static string PlayerNotFound {
            get {
                return ResourceManager.GetString("PlayerNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter the name of two players!.
        /// </summary>
        internal static string PlayersNamesRequired {
            get {
                return ResourceManager.GetString("PlayersNamesRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get players stats.
        /// </summary>
        internal static string PlayersStats {
            get {
                return ResourceManager.GetString("PlayersStats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get 10 Latest Match stats of a player.
        /// </summary>
        internal static string RecentsStats {
            get {
                return ResourceManager.GetString("RecentsStats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove the notifier.
        /// </summary>
        internal static string RemoveWatch {
            get {
                return ResourceManager.GetString("RemoveWatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requested!.
        /// </summary>
        internal static string Requested {
            get {
                return ResourceManager.GetString("Requested", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get players Solo Stats.
        /// </summary>
        internal static string SoloStats {
            get {
                return ResourceManager.GetString("SoloStats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Players Squads Stats.
        /// </summary>
        internal static string SquadStats {
            get {
                return ResourceManager.GetString("SquadStats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you!.
        /// </summary>
        internal static string Thanks {
            get {
                return ResourceManager.GetString("Thanks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is a service where you can add a pubg player to your watch and whenever that player gets a chicken dinner or top10 you will get a message from me with the stats of that match (included teammates).
        /// </summary>
        internal static string Watch {
            get {
                return ResourceManager.GetString("Watch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Watch is successfully removed!.
        /// </summary>
        internal static string WatchRemovedSuccess {
            get {
                return ResourceManager.GetString("WatchRemovedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have no watches to remove.
        /// </summary>
        internal static string YouHaveNoWatches {
            get {
                return ResourceManager.GetString("YouHaveNoWatches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your players: .
        /// </summary>
        internal static string YourPlayers {
            get {
                return ResourceManager.GetString("YourPlayers", resourceCulture);
            }
        }
    }
}
